"""empty message

Revision ID: 2cc5f25c3702
Revises: 
Create Date: 2018-05-30 15:06:01.673183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc5f25c3702'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(length=64), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_count'), 'events', ['count'], unique=False)
    op.create_index(op.f('ix_events_date'), 'events', ['date'], unique=False)
    op.create_index(op.f('ix_events_place'), 'events', ['place'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_place'), table_name='events')
    op.drop_index(op.f('ix_events_date'), table_name='events')
    op.drop_index(op.f('ix_events_count'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
