"""empty message

Revision ID: c65029dc41e2
Revises: c44553f76ae0
Create Date: 2018-05-30 17:52:06.023256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c65029dc41e2'
down_revision = 'c44553f76ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_count', table_name='events')
    op.drop_index('ix_events_date', table_name='events')
    op.drop_index('ix_events_place', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('place', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'events_pkey')
    )
    op.create_index('ix_events_place', 'events', ['place'], unique=True)
    op.create_index('ix_events_date', 'events', ['date'], unique=False)
    op.create_index('ix_events_count', 'events', ['count'], unique=False)
    # ### end Alembic commands ###
