"""empty message

Revision ID: ed0bed7c0b85
Revises: 
Create Date: 2018-05-31 12:17:24.803855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0bed7c0b85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(length=64), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('lasttweet', sa.BigInteger(), nullable=True),
    sa.Column('initialtweet', sa.BigInteger(), nullable=True),
    sa.Column('backwards', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_count'), 'events', ['count'], unique=False)
    op.create_index(op.f('ix_events_date'), 'events', ['date'], unique=False)
    op.create_index(op.f('ix_events_initialtweet'), 'events', ['initialtweet'], unique=True)
    op.create_index(op.f('ix_events_lasttweet'), 'events', ['lasttweet'], unique=True)
    op.create_index(op.f('ix_events_place'), 'events', ['place'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_place'), table_name='events')
    op.drop_index(op.f('ix_events_lasttweet'), table_name='events')
    op.drop_index(op.f('ix_events_initialtweet'), table_name='events')
    op.drop_index(op.f('ix_events_date'), table_name='events')
    op.drop_index(op.f('ix_events_count'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
