from TwitterAPI import TwitterAPI

#Secret API codes
API_KEY = 'AFuNXw2BOSv2q6CaFHVt7J203'
API_SECRET = 'htKlqfNY66HjDbl1QgV3aoVmb8MSQfUdjeIGtAIiZFJUXLu65B'
ACCESS_TOKEN = '3195815604-1IpIGAHQ4gf8QtcyIpN5QExtP3Puu2QymFNMKLv'
ACCESS_TOKEN_SECRET = '3mYL1exnSAkC2wieSHAteDdGvFuB0DMV4bVytagT2eh2i'


def get_api():
    api = TwitterAPI(API_KEY, API_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
    return api
